### ISSUE TITLE
[D3D9] Full screen hook not working

### ISSUE THREAD

**Issue by xHeisa** [Rebzzel/kiero#10]
Hello. I am hooking Reset and Present like this but it does not seem to work when the game is in full screen. 

```cpp
#define KIERO_USE_MINHOOK    1
```

```cpp
	if (kiero::init(kiero::RenderType::D3D9) == kiero::Status::Success)
	{
		kiero::bind(16, (void**)&context::reset_original, context::reset_hook);

		kiero::bind(17, (void**)&context::present_original, context::present_hook);
	}

```
Present never gets called, but it works fine in borderless / windowed mode. 
The game's name is Rocket League. 
Thanks in advance.

**Comment by Rebzzel** [comment]
Hello, @xHeisa!

How do you check that Present is not called? 
Using the debugger, console print or calls draw functions?

If you using console print you should keep in mind that the function will **only be called when the game window is expanded.**
If debugger or drawing function, then you might want to try playing with [this parameter](https://github.com/Rebzzel/kiero/blob/cdc11314f21de21dfc22461a67c2f8e384c4a78a/kiero.cpp#L121).

I don't have this game so I can't check it out. But in the games I tested, everything worked fine.

Have a nice day!

**Comment by xHeisa** [comment]
> Hello, @xHeisa!

Hello, @Rebzzel , thank you for taking the time to reply on the issue I'm having. 

> How do you check that Present is not called?
> Using the debugger, console print or calls draw functions?

I am printing with console prints.

I have added some message boxes in the source code to see where it is failing, it seems to be entering here:

https://github.com/Rebzzel/kiero/blob/master/kiero.cpp#L129

> If debugger or drawing function, then you might want to try playing with [this parameter](https://github.com/Rebzzel/kiero/blob/cdc11314f21de21dfc22461a67c2f8e384c4a78a/kiero.cpp#L121).

I have tried to change that parameter, but to no avail.

**Comment by Rebzzel** [comment]
Hmm, it looks weird.

Try to see what CreateDevice returns.
It must be something from [here](https://docs.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-idirect3d9-createdevice#return-value).

Have a nice day!

**Comment by Rebzzel** [comment]
Veeeeeeery weird, because everything works fine for me.

![proof](https://user-images.githubusercontent.com/30433331/77244059-3a3d3880-6c22-11ea-885d-2f7f9eec1e9b.gif)

**Comment by xHeisa** [comment]
Thank you for confirming my doubts about this hook, it turns out it might actually be from the renderer I am using

https://github.com/yazzn/renderer_d3d9

**Comment by Rebzzel** [comment]
Yes, I encountered the same problem when testing the imgui example. 
[Here](https://github.com/Rebzzel/kiero/blob/65262b733eaf7635ef6d9cea20dbe2eb607a3de6/examples/imgui/impl/d3d9_impl.cpp#L21) is my solve.
Try to see probably it will give you an idea.

Good luck, @xHeisa!

**Comment by xHeisa** [comment]
@Rebzzel again, thank you. Would it be possible for you to also try that d3d9 renderer ? 
I am not sure what needs to be "reset" from that renderer.
It's drawing really fast, but I think that's causing the black screen.

**Comment by Rebzzel** [comment]
Hmm. I think the solution to the problem for this render is quite simple. 

Since the author didn't bother to write the reset function, you will have to do it yourself. This will be easy enough to do. 

See how this is done in imgui: 
https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_dx9.cpp#L275 
https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_dx9.cpp#L247

You will need to do the same with these parameters:
https://github.com/yazzn/renderer_d3d9/blob/master/renderer/renderer.hpp#L102
https://github.com/yazzn/renderer_d3d9/blob/master/renderer/renderer.hpp#L103
https://github.com/yazzn/renderer_d3d9/blob/master/font/font.hpp#L49

And call your received result as [here](https://github.com/Rebzzel/kiero/blob/65262b733eaf7635ef6d9cea20dbe2eb607a3de6/examples/imgui/impl/d3d9_impl.cpp#L21).

**Comment by xHeisa** [comment]
@Rebzzel The author of the renderer seems to have wrote those functions:
https://github.com/yazzn/renderer_d3d9/blob/master/renderer/renderer.cpp#L18 
https://github.com/yazzn/renderer_d3d9/blob/master/renderer/renderer.cpp#L77

Now I'm calling those functions in Reset, and everything seems working good, except resolution changes, that renderer does not seem to account for that, causing drawings to be miss-positioned if you change the resolution. 

Thank you for your help and your example implementations, fixed a few bugs too!
