### ISSUE TITLE
Useless assertion

### ISSUE THREAD

**Issue by kernel32** [Rebzzel/kiero#11]
https://github.com/Rebzzel/kiero/blob/master/kiero.cpp#L691
https://github.com/Rebzzel/kiero/blob/master/kiero.cpp#L711
Just FYI, these assertions will never fail - _index is an _unsigned_ integer, meaning it will always be larger than or equal to zero.

**Comment by Rebzzel** [comment]
Hello, @kernel32!

Yes, that's a good point. This was due to the fact that the variable was of the short type at the beginning of development.

This will be fixed in the next commit.

Thank you.
Have a nice day!
