### ISSUE TITLE
Can't unload

### ISSUE THREAD

**Issue by Kontrol-69** [Rebzzel/kiero#14]
So, I've gotten Kiero to hook d3d11 like intended. But, when i try to unload, it just crashes.

```
void Remove(HWND hWindow)
{
	SetWindowLongPtr(hWindow, GWLP_WNDPROC, (LONG_PTR)oWndProc);
}

void hook_dx11()
{
	if (kiero::init(kiero::RenderType::D3D11) == kiero::Status::Success)
		assert(kiero::bind(8, (void**)&phookD3D11Present, PresentHook) == kiero::Status::Success);
}

void remove_dx11()
{
	kiero::unbind(8);

	g_pd3dDevice->Release();
	g_pd3dContext->Release();

	ImGui_ImplWin32_Shutdown();
	ImGui_ImplDX11_Shutdown();
	ImGui::DestroyContext();

	Remove(FindWindow(NULL, L"Call of Duty®: Black Ops II - Multiplayer"));
}

void Thread(HMODULE module)
{
	hook_dx11();

	while (true)
	{
		if (GetAsyncKeyState(VK_DELETE) & 0x8000)
			break;
	}

	remove_dx11();

	FreeConsole();
	FreeLibraryAndExitThread(module, NULL);
}
```

**Comment by Rebzzel** [comment]
Hello, @Kontrol-69!
You should check whether the crash actually occurs during uninit
Have a nice day!

**Comment by Rebzzel** [comment]
I assume that because of these two lines, there is a crash:
```C++
g_pd3dDevice->Release();
g_pd3dContext->Release();
```

**Comment by Kontrol-69** [comment]
> I assume that because of these two lines, there is a crash:
> 
> ```C++
> 
> g_pd3dDevice->Release();
> 
> g_pd3dContext->Release();
> 
> ```

Figured it out, wasn’t Kiero crashing me. Just having ImGui files in my project crashed me. Fixed now :)

**Comment by emlin2019** [comment]
Could you tell me how you fixed it? Im using this: https://github.com/rdbo/ImGui-DirectX-11-Kiero-Hook
And it crashes whenever I try to unload it using FreeLibraryAndExitThread
