### ISSUE TITLE
How to Compile the Code?

### ISSUE THREAD

**Issue by WafflesJohnny** [Rebzzel/kiero#16]
So from the read me provided with this repo, I understand you have to write your hook depending on what you want to do. 

What I don't understand is; after writing it, how do you compile the code? I don't know what to do from there.

Also, I get this error upon start-up: 

```
CMake Error at C:\Users\User Name\Source\Repos\kiero\examples\imgui\imgui\examples\example_glfw_vulkan\CMakeLists.txt:23 (add_subdirectory):
  add_subdirectory given source "../../../glfw" which is not an existing
  directory.	imgui_example_glfw_vulkan	C:\Users\User Name\Source\Repos\kiero\examples\imgui\imgui\examples\example_glfw_vulkan\CMakeLists.txt	23	
```

I did some study on CMake, and I understand that it is a utility for helping to build the project. In the CMakeLists.txt file, are you supposed to provide the address to the .cpp file containing your hooking functionality?

If anyone can lead me in the right direction, that would be great. Thank you.

**Comment by Rebzzel** [comment]
Hello, @WafflesJohnny!

This error is related to ImGui example.
It doesn't affect how the hook works, so it can be deleted.
Otherwise, I don't quite understand your issue.

Have a nice day!

**Comment by WafflesJohnny** [comment]
Oh okay, I thought maybe that was related to compiling code. Well, I'm interested in writing a hook that retrieves vertex buffer information. Based on your example code, I can write something like that; but I don't know how to compile the code to actually put it to use? I guess its not really an issue, maybe just a lack of understanding on my part. Thank you.

**Comment by Rebzzel** [comment]
Have you ever worked with hooks?

**Comment by WafflesJohnny** [comment]
No I have not. Only read tutorials.

**Comment by Rebzzel** [comment]
Then you need to learn a lot to understand how it works.

**Comment by WafflesJohnny** [comment]
Okay, I will continue my research then. Thank you.
