### ISSUE TITLE
Given that the size of feature levels is 2, should we pass in 2 here?

### ISSUE THREAD

**Issue by joshli** [Rebzzel/kiero#17]
https://github.com/Rebzzel/kiero/blob/d23d99c104494e405e568f1fcde1b1bfc77c0ea8/kiero.cpp#L332

**Comment by joshli** [comment]
Thanks for the library by the way!

**Comment by Rebzzel** [comment]
Hello, @joshli!

Yes, you right (but it doesn't really change anything).
This will be fixed the next commit.

Thank you!
Have a nice day!
