### ISSUE TITLE
unresolved symbol

### ISSUE THREAD

**Issue by iraizo** [Rebzzel/kiero#19]
<a href="https://hastebin.com/leliqazave.cpp">main.cpp</a>
<a href="https://hastebin.com/ufequfojew.cpp">main.hpp</a>

<a href="https://hastebin.com/erunugimef.bash">cmakelists.txt</a>

compiler: cmake 9.0.0 LLVM 

errors: <a href="https://hastebin.com/ecupamovic.rb">https://hastebin.com/ecupamovic.rb</a>

**Comment by Rebzzel** [comment]
Hello, @iraizo. 
Maybe try add kiero.cpp to cmakelists.txt?

**Comment by iraizo** [comment]
> 
> 
> Hello, @iraizo.
> Maybe try add kiero.cpp to cmakelists.txt?

bruh i am actually braindead i forgot that, sorry for the inconvenience
