### ISSUE TITLE
Wrong ID for SetTexture on d3d9

### ISSUE THREAD

**Issue by DevCortez** [Rebzzel/kiero#24]
On the index table, SetTexture is supposed to be 65 on d3d9, but the actual function there points to SetTexture_FP

![image](https://user-images.githubusercontent.com/2830351/98152251-2e03a400-1eb0-11eb-81cc-cdc67ec67c9b.png)

The actual address is in a different table
![image](https://user-images.githubusercontent.com/2830351/98153551-23e2a500-1eb2-11eb-8578-79398d2d582e.png)

Any clues what could be causing this?

**Comment by Rebzzel** [comment]
Hello, @DevCortez.

Hmm, interesting. I don't know what this might be related to. Try to find out what _FP means.
But I think these functions are the same.
Also, I don't think you need to worry about this, because the program will still call 65 when it calls SetTexture.

Have a nice day!

**Comment by DevCortez** [comment]
Yeah, it seems the application i'm trying to hook just doesn't call settexture the way i expected it to, there is something very shady going on but i guess you are right, in fact, the vftable seems to be just right (at least the semantic of it).

One peculiar detail i noticed tho and i'm not sure where i could ask you that so ill take the opportunity: You treat functions as _stdcall and set the first parameter as _this_, in the code i always see a plus 4 in the ret (a function with 2 args rets 0xC for instance), do you know if this is consistent with interface methods? Its a bit of an oddity because i expected it to be on ECX as usual (even prepared myself to inline a correction to set ecx to a variable on detours).

**Comment by Rebzzel** [comment]
This is because DirectX is a C compatible project (look at d3d9.h for example), and in C __thiscall does not exist, so this is passed as a normal function argument. 
For normal C++ interfaces, this will always be passed to ecx (unless we take into account some compiler optimization cases).

**Comment by DevCortez** [comment]
> This is because DirectX is a C compatible project (look at d3d9.h for example), and in C __thiscall does not exist, so this is passed as a normal function argument.
> For normal C++ interfaces, this will always be passed to ecx (unless we take into account some compiler optimization cases).

Living and learning :) Thanks for the explanation, ill close the issue to keep things clean.
