### ISSUE TITLE
custom argument to hkPresent

### ISSUE THREAD

**Issue by Detector-I** [Rebzzel/kiero#26]
Hi, sorry for this noob question
I just started to work with c++ and kiero today, so I dont know anything

I want to know its possible to pass extra argument to hkPresent?
curently its look like this in **d3d11_impl.cpp**
```c++
long __stdcall hkPresent11(IDXGISwapChain* pSwapChain, UINT SyncInterval, UINT Flags)
{
    //some code
}
```
its possible to pass some extra argument to it?
so lets say in **main.cpp** we have `impl::d3d11::init(1);`, and in **d3d11_impl.cpp** `void impl::d3d11::init(int arg)`
how can i pass it to 
```c++
assert(kiero::bind(8, (void**)&oPresent, hkPresent11) == kiero::Status::Success);
```
and get it in `__stdcall hkPresent11`?
and one other time sorry for noob question

**Comment by Rebzzel** [comment]
Happy New Year, @Detector-I!

Directly - no. We can't force every piece of code that calls this function to do an additional "push" (see how functions are called in assembler to understand what I mean).

But, we can, for example, add a global variable that will be used in the function body:
```C++

static int g_your_cool_arg = 0;

void impl::d3d11::init(int your_cool_arg)
{
   g_your_cool_arg = your_cool_arg;
   assert(kiero::bind(8, (void**)&oPresent, hkPresent11) == kiero::Status::Success);
}

long __stdcall hkPresent11(IDXGISwapChain* pSwapChain, UINT SyncInterval, UINT Flags)
{
   printf("Cool arg value: %i", g_your_cool_arg);
   // Other magic...
}

```
In fact, it has a lot of solutions, just you need to learn C++.

Good luck!

**Comment by Detector-I** [comment]
yes you right, there is lot of option
for that I create a namespace and add all of my needed variable in it, and then use it where I need them
Thanks for the tips
