### ISSUE TITLE
Is this a problem ?

### ISSUE THREAD

**Issue by ESP0xA** [Rebzzel/kiero#27]
in readme file :
```C++
  if (kiero::init(kiero::RenderType::D3D9) == kiero::Status::Success)                     // 1
  // or
  if (kiero::init(kiero::RenderType::Auto) == kiero::Status::Success)                      // 2
  {
    // define KIERO_USE_MINHOOK must be 1
    // the index of the required function can be found in the METHODSTABLE.txt
    kiero::bind(42, (void**)&oEndScene, hkEndScene);
    
    // If you just need to get the function address you can use the kiero::getMethodsTable function
    oEndScene = (EndScene)kiero::getMethodsTable()[42];
  }
```
the execution flow will go through the `1` condition, then it will skip the `2` body, am I right?
So, the hook can not be done. 
It should be:
```C++
  if (kiero::init(kiero::RenderType::D3D9) == kiero::Status::Success ||                   // 1
      kiero::init(kiero::RenderType::Auto) == kiero::Status::Success)                      // 2
  {
    // define KIERO_USE_MINHOOK must be 1
    // the index of the required function can be found in the METHODSTABLE.txt
    kiero::bind(42, (void**)&oEndScene, hkEndScene);
    
    // If you just need to get the function address you can use the kiero::getMethodsTable function
    oEndScene = (EndScene)kiero::getMethodsTable()[42];
  }
```
So that whatever we choose, d3d9 or auto, it will always complete the hook.
Am I right?
BTW, thnx for your project, I love the code.

**Comment by Rebzzel** [comment]
Hello, @ESP0xA!

You should look [here](https://github.com/Rebzzel/kiero/blob/e7de8ecc3747100b5deceec2eb3f313a26aa3994/kiero.cpp#L639) and [here](https://github.com/Rebzzel/kiero/blob/e7de8ecc3747100b5deceec2eb3f313a26aa3994/kiero.cpp#L666).
**Never need** to use them together (use ONLY `Render::{TARGET_LIB_NAME}` or ONLY `RenderType::Auto`). 
Just choose what is more convenient for you.

`RenderType::Auto` just detect the type of library that is used.
This is useful if you are making a universal library ([example](https://github.com/Rebzzel/kiero/blob/e7de8ecc3747100b5deceec2eb3f313a26aa3994/examples/imgui/main.cpp#L32)).
By the way, nothing terrible will happen if you use them together (but please don't do that) - the kiero simply [will not allow you](https://github.com/Rebzzel/kiero/blob/e7de8ecc3747100b5deceec2eb3f313a26aa3994/kiero.cpp#L50) to init it again.

#### Not relevant to the topic, but perhaps someone does not understand:
The kiero allows you to use all the hooks (just setting up all `KIERO_INCLUDE_...` to 1).

Thank you for your respect!
Have a nice day!

**Comment by ESP0xA** [comment]
Thnx for the explanation @Rebzzel 
Your project works fine in my test now, but the auto-detection is not accurate.
Normally, a game rendering in one d3d version would contains some other d3d version modules(for instance, csgo, gta5). A Vulkan API game will load the d3d module at runtime either(doom eternal). 
But it's enough for me to use the main code, and I'm adding the imgui to each hook. Thnx for your work again.

**Comment by Rebzzel** [comment]
Yes, I know. I have plans to update the api to fix this, but I'm busy with other projects right now.

I actually have a lot of plans for the update, so wait.

Thank you for your appreciation.
Good luck!
