### ISSUE TITLE
OpenGL

### ISSUE THREAD

**Issue by NullifiedMistake** [Rebzzel/kiero#28]
How do I make this work with OpenGL 3 ?
idk why OpenGL 3 method table doesn't contain wglSwapBuffers
help

**Comment by Rebzzel** [comment]
Hello, @NullifiedMistake!

I think you should watch [**this**](https://stackoverflow.com/questions/15753840/where-is-glswapbuffers-defined).
All exported characters were taken from the GL.h header.
But if you still want to export this symbol, you can add it [**here**](https://github.com/Rebzzel/kiero/blob/master/kiero.cpp#L532-L562) (just add "wglSwapBuffers" to the end of the list).
The index will be 336.

Good luck!
