### ISSUE TITLE
windows 10 

### ISSUE THREAD

**Issue by Dj-jom2x** [Rebzzel/kiero#3]
i dont understand why is not working.

i compile it and follow ur readme demo
but when i inject nothing happen .. should i install something else?

i had

vstudio 2017 / dx sdk june 2010 .. complete c++ redist

**Comment by Rebzzel** [comment]
You did this in kiero.cpp?
![default](https://user-images.githubusercontent.com/30433331/52897161-60ec9c80-31e2-11e9-88fe-8f371960c186.png)

**Comment by Dj-jom2x** [comment]
i did that and add some console on app.. it called end scene but one time only and crashes..

**Comment by Dj-jom2x** [comment]
never mind it works now xD hahaha
