### ISSUE TITLE
Support for D3D9EX

### ISSUE THREAD

**Issue by breadbyte** [Rebzzel/kiero#31]
Hello! 

Firstly, thank you for making this library! 
I am using this library for quite some time now, and I noticed that a game that I'm trying to hook to is using D3D9Ex instead of D3D9.

Hooking this game through D3D9 works just fine, but the game calls D3D9Ex's `PresentEx` instead of D3D9's `Present`, which is causing weird issues with imgui and my code.

I have written a basic implementation of this over at my [fork](https://github.com/breadbyte/kiero/tree/d3d9ex-support) based on your d3d9 code, and I am actively using this code in my personal projects.

This code does work and function correctly (I am now able to hook `PresentEx`), but the reason why I have not created a pull request is because I am having a conflicted standpoint: is it more correct to add it as an "extension" to D3D9, or as it's own separate RenderType?

I would love to discuss this for code review, and hopefully add it to this repository.
Thank you!

**Comment by Rebzzel** [comment]
Hello, @breadbyte!

I'm glad you found the library useful.

### Let's talk about feature:
D3D9 and D3D9Ex use the same functions to create and use the same objects (ref. d3d9.pdb), 
so I guess it's enough to change the number of copied elements (119 to 134) in the d3d9 hook.
**I don't have much time to test this right now, so I ask you to test it yourself and tell me about the result.**

### And now about your code:
You have implemented this feature correctly, but there is a comment:

You get a two unnecessary operations when you do [this](https://github.com/breadbyte/kiero/blob/c55009fe901b6cf897b0807714283e4a411cf9e9/kiero.cpp#L168) and [this](https://github.com/breadbyte/kiero/blob/c55009fe901b6cf897b0807714283e4a411cf9e9/kiero.cpp#L193). The functions that you call fill these variables with the necessary values themselves.

Fix:

```C++
LPDIRECT3D9EX direct3D9;
(((HRESULT(__stdcall*)(uint32_t, LPDIRECT3D9EX*))(Direct3DCreate9Ex))(D3D_SDK_VERSION, &direct3D9));
if (direct3D9 == NULL)
...
```
and:
```C++
LPDIRECT3DDEVICE9EX device;
if (direct3D9ex->CreateDeviceEx(D3DADAPTER_DEFAULT, D3DDEVTYPE_NULLREF, window, D3DCREATE_SOFTWARE_VERTEXPROCESSING | D3DCREATE_DISABLE_DRIVER_MANAGEMENT, &params, NULL, &device) < 0)
...
```

Thank you for developing the project. 
This will be added in 1.13.
Have a nice day!

**Comment by breadbyte** [comment]
Hello! 

Thank you for the response!

> D3D9 and D3D9Ex use the same functions to create and use the same objects (ref. d3d9.pdb),
so I guess it's enough to change the number of copied elements (119 to 134) in the d3d9 hook.
I don't have much time to test this right now, so I ask you to test it yourself and tell me about the result.

I have tested this with the D3D9 code, and I can confirm that this works too. Hooking D3D9Ex functions within a D3D9 application crashes the application though, which I am particularly worried about.

Thank you for the code review. I'm still learning C++ and I am still having a little bit of trouble figuring out pointers and addresses. I was having trouble with D3D9Ex's return values, and this was the first thing I can think of. Thank you for the fix!
(having `LPXX` structures doesn't help for sure 🥴)

**Comment by Rebzzel** [comment]
Thank you for testing.
