### ISSUE TITLE
upgrading problem

### ISSUE THREAD

**Issue by DoctorYasin** [Rebzzel/kiero#32]
I'm using an old version of kiero I don't know how to switch it to the new version. Can you help me?

Present oPresent;
HWND window = NULL;
WNDPROC oWndProc;
ID3D11Device* pDevice = NULL;
ID3D11DeviceContext* pContext = NULL;
ID3D11RenderTargetView* mainRenderTargetView;

void InitImGui()
{
	try
	{
		ImGui::CreateContext();
		ImGuiIO& io = ImGui::GetIO();
		io.ConfigFlags = ImGuiConfigFlags_NoMouseCursorChange;
		ImGui_ImplWin32_Init(window);
		ImGui_ImplDX11_Init(pDevice, pContext);
	} // 
	catch (...) {}
}

LRESULT WndProc(const HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam) {

	try
	{
		if (true && ImGui_ImplWin32_WndProcHandler(hWnd, uMsg, wParam, lParam))
			return true;

		return CallWindowProc(oWndProc, hWnd, uMsg, wParam, lParam);
	}
	catch (...) { return CallWindowProc(oWndProc, hWnd, uMsg, wParam, lParam); }
}

bool init = false;
HRESULT hkPresent(IDXGISwapChain* pSwapChain, UINT SyncInterval, UINT Flags)
{
	try
	{
		if (!init)
		{
			if (SUCCEEDED(pSwapChain->GetDevice(__uuidof(ID3D11Device), (void**)&pDevice)))
			{
				pDevice->GetImmediateContext(&pContext);
				DXGI_SWAP_CHAIN_DESC sd;
				pSwapChain->GetDesc(&sd);

				window = sd.OutputWindow;

				ID3D11Texture2D* pBackBuffer;
				pSwapChain->GetBuffer(0, __uuidof(ID3D11Texture2D), (LPVOID*)&pBackBuffer);
				if (pBackBuffer != 0x0) // pbackbuffer 0x0'e eşit olmaması lazım yoksa render fonksiyonu çalışmaz
					// oyuzden önce kontrol etmen lazım
					pDevice->CreateRenderTargetView(pBackBuffer, NULL, &mainRenderTargetView); // this crashes
				pBackBuffer->Release(); // de

				oWndProc = (WNDPROC)SetWindowLongPtr(window, GWLP_WNDPROC, (LONG_PTR)WndProc);
				InitImGui();
				init = true;
			}
			else
			{
				return oPresent(pSwapChain, SyncInterval, Flags);
			}
		}
		
				pContext->OMSetRenderTargets(1, &mainRenderTargetView, NULL);
		ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());
		return oPresent(pSwapChain, SyncInterval, Flags);
	}
	catch (...) { return oPresent(pSwapChain, SyncInterval, Flags); }
	
	
	DWORD WINAPI GUI::MainThread()
{
	try
	{
		std::cout << "Trying to hook overlay" << std::endl;
		//bool init_hook = false;
		while (true)
		{
			if (kiero::init(kiero::RenderType::D3D11) == kiero::Status::Success)
			{
				kiero::bind(8, (void**)&oPresent, hkPresent);
				//init_hook = true;
				break;
			}
			else
			{
				std::cout << "Code returned from overlay" << kiero::init(kiero::RenderType::D3D11) << std::endl;
				break;
			}
		}
	}
	catch (...) { MessageBoxA(NULL, "Overlay Crashed", "X", MB_OK); }

	return TRUE;
}

BOOL WINAPI DllMain(HMODULE hMod, DWORD dwReason, LPVOID lpReserved)
{
	switch (dwReason)
	{
	case DLL_PROCESS_ATTACH:
		DisableThreadLibraryCalls(hMod);
		CreateThread(nullptr, 0, (LPTHREAD_START_ROUTINE)Core::Init, hMod, 0, nullptr);
		break;
	case DLL_PROCESS_DETACH:
		kiero::shutdown();
		break;
	}

	return TRUE;
}

I don't know how to translate this into a new kiero.

**Comment by Rebzzel** [comment]
Just replace kiero.cpp and kiero.h?

**Comment by DoctorYasin** [comment]
I don't know how to update the code named (present) to the existing new codes.

**Comment by Rebzzel** [comment]
API wasn't changed since v1.2.6. Don't understand you.
