### ISSUE TITLE
hook  windows dwm

### ISSUE THREAD

**Issue by zhongguo1987** [Rebzzel/kiero#33]
I think hook windows DWM, but I can't find DirectX related dynamic library in DWM. DirectX exists in dwmcore.dll loaded by DWM. What can I do to use this library

**Comment by Rebzzel** [comment]
Inject your code into dwm.exe?

**Comment by zhongguo1987** [comment]
hook directx's  DXGISwapPresent

**Comment by zhongguo1987** [comment]
> Inject your code into dwm.exe?

I Want to hook DXGISwapPresent，capture desktop images

**Comment by Rebzzel** [comment]
> DXGISwapPresent
You mean IDXGISwapChain::Present?

**Comment by zhongguo1987** [comment]
> > DXGISwapPresent
> 
> You mean IDXGISwapChain::Present?

yes,I use the ultimate version of win7 SP1, through hook, in the module can not find DXGI, debug code tracking, win7 uses D3D10_ 1 version, you develop this library is very good, what method can support, thank you

**Comment by Rebzzel** [comment]
https://github.com/Rebzzel/kiero/blob/35d4e4f7510f9123646f759beede172d22a85650/kiero.cpp#L239

So the index is 8:

https://github.com/Rebzzel/kiero/blob/35d4e4f7510f9123646f759beede172d22a85650/METHODSTABLE.txt#L131

**Comment by zhongguo1987** [comment]
> https://github.com/Rebzzel/kiero/blob/35d4e4f7510f9123646f759beede172d22a85650/kiero.cpp#L239
> 
> So the index is 8:
> 
> https://github.com/Rebzzel/kiero/blob/35d4e4f7510f9123646f759beede172d22a85650/METHODSTABLE.txt#L131

thank you,I try it .
