### ISSUE TITLE
DX11HOOK

### ISSUE THREAD

**Issue by VTLOWKEY** [Rebzzel/kiero#35]
Do you have The Dx11 VTable Hook ImGui
My Code is all right, but it doesn't respond~
![S2C@)GSOG0E3D$SX~QL_4%O](https://user-images.githubusercontent.com/83869428/125137452-49116c80-e13f-11eb-8298-747340eb991d.png)

**Comment by Rebzzel** [comment]
I have a few questions for you: 
Do you know what the word "or" means? 
Do you understand what "auto" means? 
Do you have the eyes to see the "examples" folder?

#27 and #34 should help you.
