### ISSUE TITLE
offer project

### ISSUE THREAD

**Issue by lifesoul24** [Rebzzel/kiero#36]
hi mate really nice project sorry to write this here, but can I have your discord id to offer freelance projects?  or if you can add me on discord : lifesoulmmkiy#6045
thank you and sorry again to write this here.

**Comment by Rebzzel** [comment]
Hello, @lifesoul24!
Check your friend requests.
Have a nice day.

**Comment by lifesoul24** [comment]
hey dude are you fixed your pc ?
