### ISSUE TITLE
Unsolved External Symbol

### ISSUE THREAD

**Issue by NotACoder1337** [Rebzzel/kiero#39]
Issue #15 had the same error but I don't know what he means by "forgot to add the include and bin folders to the project using the buttons in vs2019" I added kiero.h, kiero.cpp, the whole impl folder, and minhook.h, in include directories. I dont know what im missing or need to do.

**Comment by Symbai** [comment]
You need to include the .lib files. You may want to google how to do that.

**Comment by Rebzzel** [comment]
Compile minhook together with the program, or include it .lib, as said above.
```C++
#pragma comment(lib, "YOUR_LIB_NAME_HERE.lib")
```

**Comment by NotACoder1337** [comment]
ok thank you

**Comment by NotACoder1337** [comment]
So I built MinHook VC9 I included it into my project and #pragma comment(lib, "MinHook.lib") put that in dllmain. I all so went into project properties > Linker > Input > Additional Dependencies, and added MinHook.lib as one. I still have the same three unresolved symbol errors.

**Comment by Rebzzel** [comment]
For some reason, your kiero.cpp it does not compile, try to upload the source code from VS and maybe I can help you.

**Comment by NotACoder1337** [comment]
Yea I went out of town for a week sorry but here it is.
![errors](https://user-images.githubusercontent.com/88123119/128582315-d215c9e3-68d5-4c24-98bd-058bdee3ce1e.PNG)
![nincludes](https://user-images.githubusercontent.com/88123119/128582320-1263d633-724f-4af5-bb48-d9c7112cd3e1.PNG)
![imports 2](https://user-images.githubusercontent.com/88123119/128582322-c71935c4-9b83-4f50-bbbd-6e1e1f80ff8e.PNG)

first image is of the errors that i get
second image is all the includes 
and third image is the include folder that i added to VC Directories

and here is the dll main
all it was is the example using DX9

`
#include "kiero.h"
#include <d3d9.h>
#include <Windows.h>
#include <assert.h>
#include "pch.h"
#pragma comment(lib, "MinHook.lib")

// Create the type of function that we will hook
typedef long(__stdcall* EndScene)(LPDIRECT3DDEVICE9);
static EndScene oEndScene = NULL;

// Declare the detour function
long __stdcall hkEndScene(LPDIRECT3DDEVICE9 pDevice)
{
    static bool init = false;
    if (!init)
    {
        MessageBox(0, "Boom! It's works!", "Kiero", MB_OK);
        init = true;
    }

    return oEndScene(pDevice);
}

int kieroExampleThread()
{
    if (kiero::init(kiero::RenderType::D3D9) == kiero::Status::Success)
        // or
        if (kiero::init(kiero::RenderType::Auto) == kiero::Status::Success)
        {
            // define KIERO_USE_MINHOOK must be 1
            // the index of the required function can be found in the METHODSTABLE.txt
            kiero::bind(42, (void**)&oEndScene, hkEndScene);

            // If you just need to get the function address you can use the kiero::getMethodsTable function
            oEndScene = (EndScene)kiero::getMethodsTable()[42];
        }

    return 0;
}

BOOL WINAPI DllMain(HINSTANCE hInstance, DWORD fdwReason, LPVOID)
{
    DisableThreadLibraryCalls(hInstance);

    switch (fdwReason)
    {
    case DLL_PROCESS_ATTACH:
        CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)kieroExampleThread, NULL, 0, NULL);
        break;
    }

    return TRUE;
}
`

**Comment by Rebzzel** [comment]
As I understand it, you just include kiero in the VC directories that are located in the project properties. This is wrong, since you just gave the VS the paths to the kiero headers (aka. .h files), but it will not compile the source code files (aka. .cpp files). You need to include kiero in the compilation, or compile kiero into a lib file. To add a file to the compilation, you need to right-click on the VS project > Add > Existing file > kiero files.

**Comment by NotACoder1337** [comment]
holy shit that worked
thanks!
