### ISSUE TITLE
Add more comment please

### ISSUE THREAD

**Issue by edoriontlg** [Rebzzel/kiero#4]
I'm trying to understand how to use your stuff properly as it seems to be very powerful, but I don't understand your example...

What's needed in your base cpp file to make it work ? How does bind work and what do you need to do to make it work ? Etc...

I think you should add more comments in the example. 

Thanks !

**Comment by Rebzzel** [comment]
Hello, @edoriontlg!

To make this work, you first need to open kiero.cpp and uncomment necessary header files of graphic libraries. (https://github.com/Rebzzel/kiero/blob/master/kiero.cpp#L8)

An example for a hook d3d10:
```C++
// Uncomment a needed graphical library (you can include all)
//#include <d3d9.h>          // D3D9
//#include <dxgi.h>          // D3D10/D3D11/D3D12 (must be included for d3d12 hook)
//#include <d3d10_1.h>       // D3D10
#include <d3d10.h>         // D3D10
#define KIERO_D3D10_USAGE  // This need because d3d11.h includes d3d10.h
//#include <d3d11.h>         // D3D11
//#include <d3d12.h>         // D3D12
//#include <gl/GL.h>         // OpenGL
//#include <vulkan/vulkan.h> // Vulkan
```
After that, proceed to the next steps:
1. Initialize kiero with the kiero::init function. (see the example in README)
2. Use kiero::hook (or kiero::getMethodsTable) for necessary functions. (the index function can be viewed in METHODSTABLE.txt)
3. Compile your project.
4. Inject the resulting DLL.

Some notes:
- To use kiero::bind you will need [MinHook](https://github.com/TsudaKageyu/minhook).
- More comments and examples will appear as soon as I have the time and desire.

If you have any questions write here.
Have a nice day!

**Comment by edoriontlg** [comment]
Thanks for the help !

I'll ask if I have any problem 👌

**Comment by edoriontlg** [comment]
I have another problem...

I created a new .dll project in vstudio 2019, added kiero and minhook, pasted your example in and added my own commands, but nothing happened when I pasted the .dll next to my game executable.

Have I done something wrong ?

**Comment by Rebzzel** [comment]
Hello, again @edoriontlg!

First you need to inject (example Extreme Injector) the dll into the executable file.
Second, I need the code to fully understand you.

Have a nice day!

**Comment by edoriontlg** [comment]
Well I took your example code :
`long __stdcall hkEndScene(LPDIRECT3DDEVICE9 pDevice)
{
	static bool init = false;
	if (!init)
	{
		MessageBox(0, L"OMG IT WORKED", L"<3", MB_OK);
		init = true;
	}
	
	return oEndScene(pDevice);
}`

and added those four lines : 
`long __stdcall hkEndScene(LPDIRECT3DDEVICE9 pDevice)
{
	static bool init = false;
	if (!init)
	{
		pDevice->SetRenderState(D3DRS_SHADEMODE, D3DSHADE_FLAT);
		pDevice->SetRenderState(D3DRS_SPECULARENABLE, FALSE);
		pDevice->SetRenderState(D3DRS_LIGHTING, FALSE);
		pDevice->ShowCursor(FALSE);

		MessageBox(0, L"OMG IT WORKED", L"<3", MB_OK);
		init = true;
	}
	
	return oEndScene(pDevice);
}`

But I havent done the dll injection. I'll try that.

My goal is to make a tool to make games run on crappy computers if you want to know.

**Comment by Rebzzel** [comment]
Just use the injector to understand that it really works.

**Comment by Rebzzel** [comment]
I also think you're doing it wrong. Try this:
```C++
long __stdcall hkEndScene(LPDIRECT3DDEVICE9 pDevice)
{
	static bool init = false;
	if (!init)
	{
		MessageBox(0, L"OMG IT WORKED", L"<3", MB_OK);
		init = true;
	}

	pDevice->SetRenderState(D3DRS_SHADEMODE, D3DSHADE_FLAT);
	pDevice->SetRenderState(D3DRS_SPECULARENABLE, FALSE);
	pDevice->SetRenderState(D3DRS_LIGHTING, FALSE);
	
	return oEndScene(pDevice);
}
```

**Comment by edoriontlg** [comment]
> I also think you're doing it wrong. Try this:
> 
> ```c++
> long __stdcall hkEndScene(LPDIRECT3DDEVICE9 pDevice)
> {
> 	static bool init = false;
> 	if (!init)
> 	{
> 		MessageBox(0, L"OMG IT WORKED", L"<3", MB_OK);
> 		init = true;
> 	}
> 
> 	pDevice->SetRenderState(D3DRS_SHADEMODE, D3DSHADE_FLAT);
> 	pDevice->SetRenderState(D3DRS_SPECULARENABLE, FALSE);
> 	pDevice->SetRenderState(D3DRS_LIGHTING, FALSE);
> 	
> 	return oEndScene(pDevice);
> }
> ```

I'll try this as soon as I can.


BTW I think the error is from me. I used this https://github.com/DarthTon/Xenos to inject the dll to csgo, but I think I've done the manipulation wrong (as I saw on internet, the app needs to be running, and I injected the dll when it wasnt)

Thanks for the help, I'll reach you out if I still have problems.
