### ISSUE TITLE
fix example??

### ISSUE THREAD

**Issue by syahmizul** [Rebzzel/kiero#48]
Was using the example to try stuff and things didn't work,
had to change this line

`kiero::bind(42, (void**)&oEndScene, hkEndScene);`
to
`kiero::bind(42, (void**)&oEndScene, &hkEndScene);`
idk maybe its just me lol

**Comment by Rebzzel** [comment]
Are you building in DEBUG mode?

**Comment by syahmizul** [comment]
Yeah,does that affect it?
