### ISSUE TITLE
I want to replace each texture in the scene by a blank texture (or change the LOD)

### ISSUE THREAD

**Issue by edoriontlg** [Rebzzel/kiero#5]
Everything is in the title. 
I want to do something like a Foreach() in c# (maybe there is a better alternative).

Thanks !!

**Comment by edoriontlg** [comment]
BTW I dont know how to setup dx10, 11, 12, Opengl and vulkan

**Comment by Rebzzel** [comment]
Hello, @edoriontlg!

If you need d3d9 look towards the [IDirect3DDevice9::SetTexture](https://github.com/Rebzzel/kiero/blob/master/METHODSTABLE.txt#L67) function. 
The rest will help you Google.

Have a nice day!
