### ISSUE TITLE
 dwm.exe hook error

### ISSUE THREAD

**Issue by aadog** [Rebzzel/kiero#50]
dwm.exe hook error

system:windows 11

**Comment by Rebzzel** [comment]
Very informative.

**Comment by aadog** [comment]
When the program is injected into the dwm.exe win11 system, it doesn't seem to draw the 11 system correctly

**Comment by aadog** [comment]
More importantly, how should I compile it? Does it have a vs project

**Comment by aadog** [comment]
Do you offer paid services

**Comment by Rebzzel** [comment]
> More importantly, how should I compile it? Does it have a vs project

Just copy to your project and uncomment needed library.

**Comment by Rebzzel** [comment]
> Do you offer paid services

Do you want to hire me?

**Comment by aadog** [comment]
yes,dwm inject how money

**Comment by aadog** [comment]
do you have a telegram？

**Comment by Rebzzel** [comment]
> yes,dwm inject how money

contact me: rebzzel@gmail.com

**Comment by aadog** [comment]
telegram? find error
